### ISSUE TITLE
Run error mxnet.base.MXNetError: [00:29:51] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

### ISSUE THREAD

**Issue by gclsoft** [jinfagang/Shadowless#1]
```
root@g-virtual-machine:/mnt/hgfs/Shadowless# python3 main.py 
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    shadowless()
  File "main.py", line 9, in shadowless
    mono_manager = MonoManager()
  File "/mnt/hgfs/Shadowless/perception/camera_manager/mono_camera_manager.py", line 26, in __init__
    self.detect_manager = DetectManager(core='ssd')
  File "/mnt/hgfs/Shadowless/perception/detect/detect_manager.py", line 16, in __init__
    from .mxnet_ssd.demo import SSDDetector
ImportError: No module named 'perception.detect.mxnet_ssd.demo'
```

demo文件夹可能忘记上传了, 会报这样的错误. 我改成:from .mxnet_ssd.mxnet_ssd_detector import MXNetSSDDetector
然后报下面的错误:

```
root@g-virtual-machine:/mnt/hgfs/Shadowless# python3 main.py 
Using mxnet as:
<module 'mxnet' from '/usr/local/lib/python3.5/dist-packages/mxnet/__init__.py'>
Warning: using pre-installed version of mxnet may cause unexpected error...
(export MXNET_EXAMPLE_SSD_DISABLE_PRE_INSTALLED=1) to prevent loading pre-installed mxnet.
[DETECT] ssd backend.
# loading checkpoints from:  /mnt/hgfs/Shadowless/perception/detect/mxnet_ssd/model/ssd_resnet50_512
[00:29:51] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.10.1. Attempting to upgrade...
[00:29:51] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[00:29:51] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [00:29:51] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x17c54c) [0x7fa2b7a4354c]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ebb9a) [0x7fa2ba1b2b9a]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef1f4) [0x7fa2ba1b61f4]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef6c7) [0x7fa2ba1b66c7]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2364ded) [0x7fa2b9c2bded]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23828a4) [0x7fa2b9c498a4]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2369fbc) [0x7fa2b9c30fbc]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x236e468) [0x7fa2b9c35468]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2375faa) [0x7fa2b9c3cfaa]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23766a4) [0x7fa2b9c3d6a4]

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/symbol/symbol.py", line 1488, in simple_bind
    ctypes.byref(exe_handle)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [00:29:51] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x17c54c) [0x7fa2b7a4354c]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ebb9a) [0x7fa2ba1b2b9a]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef1f4) [0x7fa2ba1b61f4]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef6c7) [0x7fa2ba1b66c7]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2364ded) [0x7fa2b9c2bded]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23828a4) [0x7fa2b9c498a4]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2369fbc) [0x7fa2b9c30fbc]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x236e468) [0x7fa2b9c35468]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2375faa) [0x7fa2b9c3cfaa]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23766a4) [0x7fa2b9c3d6a4]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    shadowless()
  File "main.py", line 9, in shadowless
    mono_manager = MonoManager()
  File "/mnt/hgfs/Shadowless/perception/camera_manager/mono_camera_manager.py", line 26, in __init__
    self.detect_manager = DetectManager(core='ssd')
  File "/mnt/hgfs/Shadowless/perception/detect/detect_manager.py", line 18, in __init__
    self.detector = MXNetSSDDetector()#SSDDetector()
  File "/mnt/hgfs/Shadowless/perception/detect/mxnet_ssd/mxnet_ssd_detector.py", line 34, in __init__
    self.detector = self._get_detector()
  File "/mnt/hgfs/Shadowless/perception/detect/mxnet_ssd/mxnet_ssd_detector.py", line 52, in _get_detector
    ctx_, len(self.classes), args_.nms_thresh, args_.force_nms)
  File "/mnt/hgfs/Shadowless/perception/detect/mxnet_ssd/mxnet_ssd_detector.py", line 68, in get_detector
    detector = Detector(net, prefix, epoch, data_shape, mean_pixels, ctx=ctx)
  File "/mnt/hgfs/Shadowless/perception/detect/mxnet_ssd/detect/detector.py", line 46, in __init__
    self.mod.bind(data_shapes=[('data', (batch_size, 3, data_shape, data_shape))])
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/module.py", line 428, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 237, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 333, in bind_exec
    shared_group))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 611, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/symbol/symbol.py", line 1494, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 512, 512)
[00:29:51] src/storage/storage.cc:118: Compile with USE_CUDA=1 to enable GPU usage

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x17c54c) [0x7fa2b7a4354c]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ebb9a) [0x7fa2ba1b2b9a]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef1f4) [0x7fa2ba1b61f4]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x28ef6c7) [0x7fa2ba1b66c7]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2364ded) [0x7fa2b9c2bded]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23828a4) [0x7fa2b9c498a4]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2369fbc) [0x7fa2b9c30fbc]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x236e468) [0x7fa2b9c35468]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x2375faa) [0x7fa2b9c3cfaa]
[bt] (9) /usr/local/lib/python3.5/dist-packages/mxnet/libmxnet.so(+0x23766a4) [0x7fa2b9c3d6a4]
 
```
How to solve it?

**Comment by lucasjinreal** [comment]
@gclsoft I just fix the mistake, you can pull your project and follow the instruction to run Shadowless.
